In [314]:
import numpy as np
import csv

def get_key1(wordlist,val):
    out = [k for k,v in wordlist.items() if v==val]
    return (''.join(out))




class numpyNN:
    def __init__(self, data, word_dim, hidden_dim, bptt_truncate=4):
                
        data = ["%s %s %s" %('start_token', x.lower(), 'end_token') for x in data]
        data = [ (sent.replace(' ',',')) for sent in data]
        data = [ sent.split(',') for sent in data]
        self.data = data
        
        
        all_words = [w for sent in self.data for w in sent]
        self.u_words = set(all_words)
        self.word_dict = dict([(w,i) for i,w in enumerate(self.u_words)])
        data_tokens = []
        for sent in self.data:
            data_tokens.append(np.array([self.word_dict[w] for w in sent]))
        self.data_tokens = data_tokens
        
        self.train_x = np.array(self.data_tokens[:-1])
        self.train_y = np.array(self.data_tokens[1:])
        
        self.word_dim = word_dim
        self.hidden_dim = hidden_dim
        self.bptt_truncate = bptt_truncate
        
        self.u = np.random.randn(self.hidden_dim,self.word_dim)
        self.v = np.random.randn(self.word_dim, self.hidden_dim)
        self.w = np.random.randn(self.hidden_dim, self.hidden_dim)
    
    
    def get_key(self,val):
        out = [k for k,v in self.word_dict.items() if v==val]
        return (''.join(out))  
    

In [315]:
vocabulary_size =100
unknown_token ="U_Token"
#start_token ="SENTENCE_START"
#end_token ="SENTENCE_END"

sentences = []
with open('./own_dataset.txt') as f:
    reader = csv.reader(f)
    sentences = [''.join(line) for line in reader]
sentences = sentences[:10]   
print(sentences[0])

In [316]:
NN = numpyNN(sentences, 10,2)
NN.data_tokens

[array([14, 17, 16,  1, 13]),
 array([14,  3, 16,  5, 13]),
 array([14,  5,  2, 10, 15,  6, 13]),
 array([14,  7, 16,  4, 13]),
 array([14,  8, 16, 18, 13]),
 array([14, 18,  2, 15, 13]),
 array([14,  9,  2, 10, 11, 13]),
 array([14,  0,  2, 10, 12, 13])]

In [323]:
xx = np.array(NN.data_tokens)
sen_o = [NN.get_key(v) for v in xx[0]]
sen_o


['start_token', 'sajeeva', 'like', 'hockey', 'end_token']

In [284]:
sentences = ["%s %s %s" %(start_token, x.lower(), end_token) for x in sentences]
sentences = [ (sent.replace(' ',',')) for sent in sentences]
sentences = [ sent.split(',') for sent in sentences]

In [232]:

sentences


[['start_token', 'sajeeva', 'like', 'hockey', 'SENTENCE_END'],
 ['start_token', 'shihan', 'like', 'cricket', 'SENTENCE_END'],
 ['start_token', 'cricket', 'is', 'a', 'fun', 'game', 'SENTENCE_END'],
 ['start_token', 'nobody', 'like', 'curling', 'SENTENCE_END'],
 ['start_token', 'dihan', 'like', 'jumping', 'SENTENCE_END'],
 ['start_token', 'jumping', 'is', 'fun', 'SENTENCE_END'],
 ['start_token', 'hansie', 'is', 'a', 'artist', 'SENTENCE_END'],
 ['start_token', 'dylan', 'is', 'a', 'gamer', 'SENTENCE_END']]

In [233]:
all_words = [w for sent in sentences for w in sent]
u_words = set(all_words)
word_dict = dict([(w,i) for i,w in enumerate(u_words)])
sentences_t = []
for sent in sentences:
    sentences_t.append([word_dict[w] for w in sent])
sentences_t

[[14, 17, 16, 1, 8],
 [14, 3, 16, 5, 8],
 [14, 5, 2, 10, 15, 6, 8],
 [14, 7, 16, 4, 8],
 [14, 9, 16, 18, 8],
 [14, 18, 2, 15, 8],
 [14, 11, 2, 10, 12, 8],
 [14, 0, 2, 10, 13, 8]]

In [197]:
sentences_w = []
for sent in sentences_t:
    sentences_w.append([get_key(word_dict,w) for w in sent])
sentences_t


[[2, 17, 16, 1, 9],
 [2, 3, 16, 6, 9],
 [2, 6, 4, 11, 15, 7, 9],
 [2, 8, 16, 5, 9],
 [2, 10, 16, 18, 9],
 [2, 18, 4, 15, 9],
 [2, 12, 4, 11, 13, 9],
 [2, 0, 4, 11, 14, 9]]

In [176]:
get_key(word_dict,15)

['fun']