In [36]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from sklearn import svm, naive_bayes, neighbors
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score, mean_squared_error, r2_score
from sklearn.pipeline import make_pipeline
from sklearn.datasets import load_wine, load_iris, load_boston


In [109]:
features, labels = load_wine(return_X_y=True)
features_scaled = StandardScaler().fit(features).transform(features)
features_scaled_pca = PCA(n_components=2).fit_transform(features_scaled)


X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=0.3,random_state=42)
model_pca = make_pipeline(PCA(n_components=2), naive_bayes.GaussianNB())
model_pca.fit(X_train,y_train)
prediction = model_pca.predict(X_test)



X_train_scaled, X_test_scaled, y_train_scaled, y_test_scaled = train_test_split(features_scaled_pca, labels, test_size=0.3,random_state=42)
model_scaled_pca = naive_bayes.GaussianNB()
model_scaled_pca.fit(X_train_scaled,y_train_scaled)
prediction_scaled = model_scaled_pca.predict(X_test_scaled)

print("accuracy w/o scaler {0}".format(metrics.accuracy_score(y_test,prediction)))
print("accuracy with scaler {0}".format(metrics.accuracy_score(y_test_scaled,prediction_scaled)))


accuracy w/o scaler 0.8148148148148148
accuracy with scaler 0.9814814814814815


In [158]:
x, y = load_wine(return_X_y=True)
y=y.reshape(-1,1)
print(y.shape)
N = len(y)
D_in, D_h, D_out =  13, 10, 1

w1 = np.random.randn(D_in, D_h)
w2 = np.random.randn(D_h, D_out)

(178, 1)


In [210]:
D_in, H, D_out = 13,100, 1
x = np.random.randn(N, D_in)
y = np.random.randn(N, D_out)

# Randomly initialize weights
w1 = np.random.randn(D_in, H)
w2 = np.random.randn(H, D_out)

learning_rate = 1e-6
for t in range(500):

  h = x.dot(w1)
  h_relu = np.maximum(h, 0)
  y_pred = h_relu.dot(w2)
  
  # Compute and print loss
  loss = np.square(y_pred - y).sum()
  #rint(t, loss)
  
  # Backprop to compute gradients of w1 and w2 with respect to loss
  grad_y_pred = 2.0 * (y_pred - y)
  grad_w2 = h_relu.T.dot(grad_y_pred)
  grad_h_relu = grad_y_pred.dot(w2.T)
  grad_h = grad_h_relu.copy()
  grad_h[h < 0] = 0
  grad_w1 = x.T.dot(grad_h)
 
  # Update weights
  w1 -= learning_rate * grad_w1
  w2 -= learning_rate * grad_w2

In [208]:
lr = 1e-6
w1 = np.random.randn(D_in, D_h)
w2 = np.random.randn(D_h, D_out)

for i in range(0,10000):
    h = x.dot(w1)
    h_relu = np.maximum(h,0)
    y_pred = h_relu.dot(w2)
    
    error = np.square(y_pred-y).sum()
    #print(error)

    grad_o = 2.0*(y_pred- y)

    grad_w2 = h_relu.T.dot(grad_o)
    grad_h_relu = grad_o.dot(w2.T)

    grad_h = grad_h_relu.copy()
    grad_h[h < 0] = 0
    grad_w1 = x.T.dot(grad_h)
    w1 -= lr*grad_w1
    w2 -= lr*grad_w2
print(error)

x_test = x[0:10]
y_test = y[0:10]

h = x_test.dot(w1)
h_relu = np.maximum(h,0)
y_pred = h_relu.dot(w2)
for i in range(len(y_test)):
    print(y_pred[i], y_test[i])

189.740007833
[-0.10756527] [-0.14652357]
[-0.08243374] [-0.00285049]
[ 0.06613395] [-1.16736161]
[ 0.05356172] [ 1.2579005]
[ 0.06550448] [ 0.84097915]
[ 0.23182481] [-0.6300162]
[-0.15439449] [ 1.98342365]
[ 0.34051247] [-1.55408156]
[-0.13015516] [ 0.15525185]
[-0.1501388] [-0.54625034]


In [174]:
error

array([[ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ nan],
       [ n

In [127]:
h_relu

array([[ 315.80740024,    0.        ,    0.        , ...,  258.84526654,
           0.        ,  444.84816555],
       [ 278.97968875,    0.        ,    0.        , ...,  204.1395723 ,
           0.        ,  446.9086231 ],
       [ 310.6750569 ,    0.        ,    0.        , ...,  208.58429757,
           0.        ,  494.28056739],
       ..., 
       [ 289.39539735,    0.        ,    0.        , ...,  256.00594641,
           0.        ,  342.51368581],
       [ 288.60395828,    0.        ,    0.        , ...,  252.05800377,
           0.        ,  342.56228863],
       [ 224.236657  ,    0.        ,    0.        , ...,  210.54718794,
           0.        ,  217.94049772]])

In [104]:
class_0 = X_train[y_train==0]
class_1 = X_train[y_train==1]
class_2 = X_train[y_train==2]

class_0_s = X_train_scaled[y_train_scaled==0]
class_1_s = X_train_scaled[y_train_scaled==1]
class_2_s = X_train_scaled[y_train_scaled==2]

print(class_0[0])

[  1.32800000e+01   1.64000000e+00   2.84000000e+00   1.55000000e+01
   1.10000000e+02   2.60000000e+00   2.68000000e+00   3.40000000e-01
   1.36000000e+00   4.60000000e+00   1.09000000e+00   2.78000000e+00
   8.80000000e+02]


In [80]:
print(class_0[0,0],class_0[0,1])

2.08452220473 -1.06113799358


In [108]:
fig, axes = plt.subplots(ncols=2, figsize=(10,10))
axes[0].scatter(class_0[:,0],class_0[:,1], color='r', marker='o', alpha=0.5)
axes[0].scatter(class_1[:,0],class_1[:,1], color='g', marker='^', alpha=0.5)
axes[0].scatter(class_2[:,0],class_2[:,1], color='c', marker='s', alpha=0.5)

axes[1].scatter(class_0_s[:,0],class_0_s[:,1], color='r', marker='o', alpha=0.5)
axes[1].scatter(class_1_s[:,0],class_1_s[:,1], color='g', marker='^', alpha=0.5)
axes[1].scatter(class_2_s[:,0],class_2_s[:,1], color='c', marker='s', alpha=0.5)


plt.show()

In [107]:
features, labels = load_wine(return_X_y=True)

X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=0.3,random_state=42)

model_pca = make_pipeline(PCA(n_components=2), naive_bayes.GaussianNB())
model_pca.fit(X_train,y_train)
prediction = model_pca.predict(X_test)


model_scaled_pca = make_pipeline(StandardScaler(), PCA(n_components=2), naive_bayes.GaussianNB())
model_scaled_pca.fit(X_train,y_train)
prediction_scaled = model_scaled_pca.predict(X_test)


accuracy = accuracy_score(y_test,prediction)
accuracy_scaled = accuracy_score(y_test,prediction_scaled)


accuracy = accuracy_score(y_test, prediction)
print('accuracy of model_nb:', accuracy)


accuracy_scaled = accuracy_score(y_test,prediction_scaled)
print('accuracy of model_nb_scaled:', accuracy_scaled)

accuracy of model_nb: 0.814814814815
accuracy of model_nb_scaled: 0.981481481481


In [21]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from sklearn import svm, neighbors, linear_model, naive_bayes
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.pipeline import make_pipeline
from sklearn.datasets import load_iris, load_wine, load_boston

In [26]:
features, labels = load_wine(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=0.3, random_state=42)

model_nb = make_pipeline(PCA(n_components=2), GaussianNB())
model_nb.fit(X_train, y_train)
prediction =  model_nb.predict(X_test)

model_nb_scale = make_pipeline(StandardScaler(), PCA(n_components=2), GaussianNB())
model_nb_scale.fit(X_train, y_train)
prediction_scaled =  model_nb_scale.predict(X_test)

print(len(features[0]))

accuracy = accuracy_score(y_test, prediction)
print('accuracy of model_nb:', accuracy)


accuracy_scaled = accuracy_score(y_test,prediction_scaled)
print('accuracy of model_nb_scaled:', accuracy_scaled)






13
accuracy of model_nb: 0.814814814815
accuracy of model_nb_scaled: 0.981481481481


In [ ]:
pca = model_nb_scale.named_steps['pca']
scaler = model_nb_scale.named_steps['standardscaler']


#x_transformed = model_nb_scale.transform(scaler.transform(train_x))
X_train_std = pca.transform(scaler.transform(X_train))


In [ ]:
X_train_std[5]

In [ ]:
FIG_SIZE = (10,10)
#fig, (ax1, ax2) = plt.subplots(ncols=2, figsize=FIG_SIZE)
fig = plt.figure("test", figsize=FIG_SIZE)
#(ax1,ax2) = Axes3D(fig,  elev=45, azim=130)
#ax = fig.(1,1, projection='3d')
ax1 = fig.add_subplot(121, projection='3d')
ax2 = fig.add_subplot(122, projection='3d')

In [ ]:
for l, c, m in zip(range(0, 3), ('blue', 'red', 'green'), ('^', 's', 'o')):
    x = X_train[y_train ==l,0]
    y = X_train[y_train ==l,1]
    z = X_train[y_train ==l,2]
    ax1.scatter(x,y,z, color=c, marker=m, alpha=0.5)

for l, c, m in zip(range(0, 3), ('blue', 'red', 'green'), ('^', 's', 'o')):
    x = X_train_std[y_train ==l,0]
    y = X_train_std[y_train ==l,1]
    z = X_train_std[y_train ==l,2]
    ax2.scatter(x,y,z, color=c, marker=m, alpha=0.5)

ax1.set_title("Training set after PCA")    
ax2.set_title("Training set after PCA with standardizer")    

for a in (ax1,ax2):
    a.set_xlabel('pca component 1')
    a.set_ylabel('pca component 2')
    a.set_zlabel('pca component 3')
    a.grid()
    

plt.show()    

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9])
b = np.array([1,0,1,0,1,1,0,0,1])
a[b==0]
#print(X_train_std[y_train==1,0])

In [ ]:
a

In [4]:
from __future__ import print_function
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics
import matplotlib.pyplot as plt
from sklearn.datasets import load_wine
from sklearn.pipeline import make_pipeline
print(__doc__)

# Code source: Tyler Lanigan <tylerlanigan@gmail.com>
#              Sebastian Raschka <mail@sebastianraschka.com>

# License: BSD 3 clause

RANDOM_STATE = 42
FIG_SIZE = (10, 7)


features, target = load_wine(return_X_y=True)

# Make a train/test split using 30% test size
X_train, X_test, y_train, y_test = train_test_split(features, target,
                                                    test_size=0.30,
                                                    random_state=RANDOM_STATE)

# Fit to data and predict using pipelined GNB and PCA.
unscaled_clf = make_pipeline(PCA(n_components=2), GaussianNB())
unscaled_clf.fit(X_train, y_train)
pred_test = unscaled_clf.predict(X_test)

# Fit to data and predict using pipelined scaling, GNB and PCA.
std_clf = make_pipeline(StandardScaler(), PCA(n_components=2), GaussianNB())
std_clf.fit(X_train, y_train)
pred_test_std = std_clf.predict(X_test)

# Show prediction accuracies in scaled and unscaled data.
print('\nPrediction accuracy for the normal test dataset with PCA')
print('{:.2%}\n'.format(metrics.accuracy_score(y_test, pred_test)))

print('\nPrediction accuracy for the standardized test dataset with PCA')
print('{:.2%}\n'.format(metrics.accuracy_score(y_test, pred_test_std)))

# Extract PCA from pipeline
pca = unscaled_clf.named_steps['pca']
pca_std = std_clf.named_steps['pca']

# Show first principal componenets
print('\nPC 1 without scaling:\n', pca.components_[0])
print('\nPC 1 with scaling:\n', pca_std.components_[0])

# Scale and use PCA on X_train data for visualization.
scaler = std_clf.named_steps['standardscaler']
X_train_std = pca_std.transform(scaler.transform(X_train))

# visualize standardized vs. untouched dataset with PCA performed
fig, (ax1, ax2) = plt.subplots(ncols=2, figsize=FIG_SIZE)


for l, c, m in zip(range(0, 3), ('blue', 'red', 'green'), ('^', 's', 'o')):
    ax1.scatter(X_train[y_train == l, 0], X_train[y_train == l, 1],
                color=c,
                label='class %s' % l,
                alpha=0.5,
                marker=m
                )

for l, c, m in zip(range(0, 3), ('blue', 'red', 'green'), ('^', 's', 'o')):
    ax2.scatter(X_train_std[y_train == l, 0], X_train_std[y_train == l, 1],
                color=c,
                label='class %s' % l,
                alpha=0.5,
                marker=m
                )

ax1.set_title('Training dataset after PCA')
ax2.set_title('Standardized training dataset after PCA')

for ax in (ax1, ax2):
    ax.set_xlabel('1st principal component')
    ax.set_ylabel('2nd principal component')
    ax.legend(loc='upper right')
    ax.grid()

plt.tight_layout()

plt.show()

Automatically created module for IPython interactive environment

Prediction accuracy for the normal test dataset with PCA
81.48%


Prediction accuracy for the standardized test dataset with PCA
98.15%


PC 1 without scaling:
 [  1.76342917e-03  -8.35544737e-04   1.54623496e-04  -5.31136096e-03
   2.01663336e-02   1.02440667e-03   1.53155502e-03  -1.11663562e-04
   6.31071580e-04   2.32645551e-03   1.53606718e-04   7.43176482e-04
   9.99775716e-01]

PC 1 with scaling:
 [ 0.13443023 -0.25680248 -0.0113463  -0.23405337  0.15840049  0.39194918
  0.41607649 -0.27871336  0.33129255 -0.11383282  0.29726413  0.38054255
  0.27507157]


In [ ]:
#df1=pd.get_dummies(df, columns=['Make','Transmission Type'])
df = pd.get_dummies(df)
data = np.array(df)

In [ ]:
X = data[:-1]
y = data[-1]


In [ ]:
doors_d = pd.get_dummies(df['Number of Doors'])
doors_d.head(5)

In [ ]:
data = {'users':['u1','u2','u3','u4']}
df = pd.DataFrame(data)

In [ ]:
dm = df.Make.astype('category').cat.codes

In [1]:
import numpy as np

In [2]:
a = np.random.randn(5,5) < 0.8

In [3]:
a

array([[ True,  True,  True,  True,  True],
       [ True, False,  True,  True,  True],
       [ True,  True, False, False,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]], dtype=bool)

In [6]:
b = np.random.randn(a.shape[0], a.shape[1])
b

array([[-0.95518669,  1.11941106,  0.06289398,  0.4728536 , -0.27957592],
       [-1.12739027,  0.10892079, -0.55631356, -0.63589718, -0.27982564],
       [ 0.37050857,  0.76235285, -0.75323354,  0.21493627,  0.16727338],
       [ 0.55832838,  1.56826117,  0.6105489 , -1.11411829,  0.37140328],
       [-1.00438394,  0.53671108, -0.27451828, -1.56283018,  1.74764082]])

In [7]:
c = np.multiply(a,b)

In [8]:
c

array([[-0.95518669,  1.11941106,  0.06289398,  0.4728536 , -0.27957592],
       [-1.12739027,  0.        , -0.55631356, -0.63589718, -0.27982564],
       [ 0.37050857,  0.76235285, -0.        ,  0.        ,  0.16727338],
       [ 0.55832838,  1.56826117,  0.6105489 , -1.11411829,  0.37140328],
       [-1.00438394,  0.53671108, -0.27451828, -1.56283018,  1.74764082]])

In [9]:
x = [(i,k) for i in range(1,3) for k in range(1,3)]

In [10]:
x

[(1, 1), (1, 2), (2, 1), (2, 2)]

In [12]:
a = [i for i in range(1,10) if i > 5]